service: inc-cg-reporter
app: inc-cg-reporter
org: edwinsteele
frameworkVersion: '2'

plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin
provider:
  name: aws
  runtime: python3.8
  profile: serverless-wordspeak-inc-reporter
  stage: prod
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:SendRawEmail
      Resource:
        - 'arn:aws:ses:us-east-1:663011419911:identity/*'
custom:
  pythonRequirements:
    dockerizePip: non-linux
    slim: true
    strip: true
    noDeploy:
      - awscli
      - docutils
    slimPatterns:
      - '**/tests/*'

package:                         
  exclude:                      
    - node_modules/**
    - venv/**
    - .idea/**
    - .tox/**
    - .mypy_cache/**
    - __pycache__/**
    - '**/__pycache__/**'
    - .github/**
    - tests/**

functions:
  generate_report:
    handler: inc_cg_reporter/app.run
    timeout: 900
    memorySize: 256
    events:
      - schedule: cron(0 12 1 * ? *)  # midday on the first of the month

